name: htpio
description: "A next-gen HTTP client for Flutter and Dart, featuring offline support, retry logic, token handling, and more."

version: 1.1.1
homepage: https://github.com/TamoorMunawar/htpio
repository: https://github.com/TamoorMunawar/htpio

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: '>=1.10.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  connectivity_plus: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.ontechinc.htpio
        pluginClass: HtpioPlugin
      ios:
        pluginClass: HtpioPlugin

  uses-material-design: true
